[config]
engine = "python"

[build]
aptPkgs = ["build-essential"]

cmds = [
  "echo Compilando motor C++...",
  "g++ motor-cpp/src/*.cpp -std=c++17 -O3 -pthread -o /app/motor_adn",
  "ls -la /app"
]

[start]
cmd = "uvicorn app.main:app --host=0.0.0.0 --port=${PORT}"
