[config]
engine = "python"

[build]
aptPkgs = ["build-essential"]

cmds = [
  "g++ motor-cpp/src/*.cpp -std=c++17 -O3 -pthread -o motor_adn"
]

[start]
cmd = "uvicorn app.main:app --host=0.0.0.0 --port=${PORT}"
